### ISSUE TITLE
Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

### ISSUE THREAD

**Issue by ab-unstable** [sinedie/SRTranslator#16]
I am not sure if its me or the code, but when trying:
```
python -m srtranslator "path\to\file.srt" -i English -o Japanese -vv
```
I get the following:
```
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\translators\selenium_utils.py", line 47, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\__main__.py", line 78, in <module>
    translator = DeeplTranslator()
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\translators\deepl.py", line 60, in __init__
    self.driver = create_driver(proxy)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\translators\selenium_utils.py", line 53, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

**Comment by sinedie** [comment]
@ab-unstable do you have firefox installed?

**Comment by ab-unstable** [comment]
Doh! I did not. It runs now but throws a keyError about the "language" token. I'll explain in another post. Thanks!

**Comment by FRDS** [comment]
I have this same issue but I already have Firefox installed. What else is missing? 

Here's my debug output:
```
INFO:root:Getting a new Proxy from https://www.sslproxies.org/
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.us-proxy.org:443
DEBUG:urllib3.connectionpool:https://www.us-proxy.org:443 "GET / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 198.199.86.11:8080
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 103.152.112.234:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 169.55.89.6:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 205.213.80.8:8009
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 162.223.94.163:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 72.169.66.253:87
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 64.27.27.104:9090
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 147.182.132.21:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 208.180.105.70:8080
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 31.220.50.16:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 141.148.63.29:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 64.225.4.81:9998
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 75.89.101.62:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 64.225.8.115:9996
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 75.89.101.60:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 138.68.60.8:3128
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 64.225.8.179:9994
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 165.227.81.188:9958
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 72.170.220.17:8080
DEBUG:urllib3.connectionpool:http://72.170.220.17:8080 "GET http://www.google.com/ HTTP/1.1" 200 7622
INFO:root:Creating Selenium Webdriver instance
DEBUG:selenium.webdriver.common.service:Started executable: `geckodriver` in a child process with pid: 2408
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:49891/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal"}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:49891
DEBUG:urllib3.connectionpool:http://localhost:49891 "POST /session HTTP/1.1" 500 245
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"session not created","message":"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '245', 'date': 'Fri, 19 May 2023 10:07:08 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
INFO:root:Installing Firefox GeckoDriver cause it isn't installed
DEBUG:webdriverdownloader.webdriverdownloader:Attempting to access URL: https://api.github.com/repos/mozilla/geckodriver/releases/latest
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 2789
DEBUG:webdriverdownloader.webdriverdownloader:Detected OS: 64bit win
INFO:webdriverdownloader.webdriverdownloader:Download URL: https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 2789
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 2789
INFO:webdriverdownloader.webdriverdownloader:Skipping download. File C:\Users\agung\webdriver\gecko\v0.33.0\geckodriver-v0.33.0-win64.zip already on filesystem.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 2789
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 2789
INFO:webdriverdownloader.webdriverdownloader:File C:\Users\agung\bin\geckodriver.exe already exists and will be overwritten.
DEBUG:selenium.webdriver.common.service:Started executable: `geckodriver` in a child process with pid: 4616
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:49903/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal"}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:49903
DEBUG:urllib3.connectionpool:http://localhost:49903 "POST /session HTTP/1.1" 500 245
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"session not created","message":"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '245', 'date': 'Fri, 19 May 2023 10:07:12 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "D:\SRTranslator\srtranslator\translators\selenium_utils.py", line 51, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
  File "C:\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\SRTranslator\srtranslator\__main__.py", line 105, in <module>
    translator = builtin_translators[args.translator](**translator_args)
  File "D:\SRTranslator\srtranslator\translators\deepl_scrap.py", line 61, in __init__
    self.driver = create_driver(proxy)
  File "D:\SRTranslator\srtranslator\translators\selenium_utils.py", line 57, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
  File "C:\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

**Comment by sinedie** [comment]
Did you change the default location of firefox installation? If so, you could create your own webdriver with that custom path and pass it as argument

**Comment by FRDS** [comment]
No, I did not change the default configuration when installing. So it's safe to assume that it's in in default install location. Just in case, my current Firefox location is in `C:\Program Files\Mozilla Firefox`.

I can try to pass that path into the webdriver, can you show me where to look and edit? Thanks.
