### ISSUE TITLE
Sometimes times out

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#7]
Is it expected?
```
size=     173kB time=00:27:23.15 bitrate=   0.9kbits/s speed=4.14e+04x    
video:0kB audio:0kB subtitle:120kB other streams:0kB global headers:0kB muxing overhead: 44.173092%
Loading /home/toprak/Anime/[One Pace][1-7] Romance Dawn [1080p]/[One Pace][3-5] Romance Dawn 03 [1080p][8F0ACC44].srt
... Translating chunk. 0 %
... Translating chunk. 10 %
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/toprak/.local/lib/python3.10/site-packages/srtranslator/__main__.py", line 81, in <module>
    srt.translate(translator, args.src_lang, args.dest_lang)
  File "/home/toprak/.local/lib/python3.10/site-packages/srtranslator/srt_file.py", line 133, in translate
    translation = translator.translate(
  File "/home/toprak/.local/lib/python3.10/site-packages/srtranslator/translators/deepl.py", line 115, in translate
    raise TimeOutException("Translation timed out")
srtranslator.translators.base.TimeOutException: Translation timed out
```

**Comment by toprak** [comment]
Translation was not empty,
I saw "[...]" in the translation, but after that srtranslator translated new sentences, so I didn't get a timeout error after seeing that "[...]"
_The translation number of sentences is equal to original text_ I do not know what that means but SRTranslator is exceeding the character limit of DeepL What I saw before I got the timeout error was 3073/3000

**Comment by sinedie** [comment]
@toprak Thank you for catching this. I wasn't taking into account breaklines in total length count. Version 0.1.6 with las commit had it fixed. Already uploaded to PyPi.

Close issue if solve. Ty

**Comment by toprak** [comment]
It seems it fixed, thank you!

**Comment by sinedie** [comment]
Could you open a new issue? to keep things in order. Ty
