### ISSUE TITLE
Error when translate to English

### ISSUE THREAD

**Issue by llitkr** [sinedie/SRTranslator#81]
`
Loading ./XXX.srt as ASS
... Exception while loading as ASS try as SRT
Loading ./XXX.srt as SRT
Backup file found = ./XXX.srt.tmp
Starting from subtitle 0
... Translating 0 %
Timed out trying to get element (XPATH = //button[@data-testid='translator-lang-option-en'] | //button[text()='English'])
Saving ./XXX.srt.tmp
Traceback (most recent call last):
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\translators\selenium_utils.py", line 89, in __init__
    self.element = find_element(*locator)
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@data-testid='translator-lang-option-en'] | //button[text()='English']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\__main__.py", line 126, in <module>
    sub.translate(translator, args.src_lang, args.dest_lang)
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\srt_file.py", line 181, in translate
    translation = translator.translate(
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 137, in translate
    self._set_destination_language(destination_language)
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 108, in _set_destination_language
    self._set_language(language, "//*[@data-testid='translator-target-lang']")
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 123, in _set_language
    Button(self.driver, "XPATH", xpath).click()
  File "C:\Users\dldbd\AppData\Local\Programs\Python\Python310\lib\site-packages\srtranslator\translators\selenium_utils.py", line 98, in __init__
    sys.exit()
SystemExit
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C6013B1F0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')': /session/a53afbad-9f06-4a68-bce5-739d4de2eb49
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C60257970>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')': /session/a53afbad-9f06-4a68-bce5-739d4de2eb49
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C60257AC0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')': /session/a53afbad-9f06-4a68-bce5-739d4de2eb49
`

I used the command from Windows' CMD
`
python -m srtranslator "./XXX.srt" -i ko -o en
`
However, only English makes error when try to translate. id(Indonesian), ja(japan) doesn't make error.

Do you know why?

**Comment by sinedie** [comment]
Look [here](https://github.com/sinedie/SRTranslator/blob/master/docs/deepl_scrap.md#supported-languages).

There are two english options for translation so deepl name it different. ```-o en``` wont work.

Use ```-o en-US``` or ```-o en-GB```
