### ISSUE TITLE
Timed out trying to get element

### ISSUE THREAD

**Issue by h9052300** [sinedie/SRTranslator#90]
Timed out trying to get element (XPATH = //button[@data-testid='translator-lang-option-zh'] | //button[text()='Chinese'])

**Comment by sinedie** [comment]
Are you translating FROM chinese or TO chinese?

**Comment by h9052300** [comment]
Translation from English to Chinese. Thx~

**Comment by sinedie** [comment]
Deepl use two chinese options for target language (TO chinese).

Those are ```zh-Hans``` for simplified and ```zh-Hant``` for traditional. Use that instead of ```zh```, this only works if translation is FROM chinese. I may update the docs soon.

pd: I don't remember if options should be case sensitive, so better write them as it is.

**Comment by h9052300** [comment]
Thank you very much.

**Comment by h9052300** [comment]
from srtranslator.translators.deepl_scrap import DeeplTranslator

translator = DeeplTranslator(driver=driver)

oo = translator.translate("going to pull the small one for auto completion and a big one for actually", 'en', "zh-Hant")
print(oo)

translator.quit()

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Python Project\flask_view\videoToOOXX\srtranslatorTest.py", line 61, in <module>
    oo = translator.translate("going to pull the small one for auto completion and a big one for actually", 'en', "zh-Hant")
  File "C:\Users\user\Desktop\Python Project\flask_view\venv\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 137, in translate
    self._set_destination_language(destination_language)
  File "C:\Users\user\Desktop\Python Project\flask_view\venv\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 108, in _set_destination_language
    self._set_language(language, "//*[@data-testid='translator-target-lang']")
  File "C:\Users\user\Desktop\Python Project\flask_view\venv\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 119, in _set_language
    x_path_by_text = f"//button[text()='{self.languages[language]}']"
KeyError: 'zh-Hant'

How can I adjust it?

**Comment by sinedie** [comment]
@h9052300  I haven't seen this, sry. Do you still have this issue? If so, pls reopen
