### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by h9052300** [sinedie/SRTranslator#97]
Traceback (most recent call last):
  File "C:\Users\x1090102\PycharmProjects\flask_view\videoToOOXX\srtranslatorTest.py", line 31, in <module>
    translator = DeeplTranslator()
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\x1090102\PycharmProjects\flask_view\venv\Lib\site-packages\srtranslator\translators\deepl_scrap.py", line 66, in __init__
    self._rotate_proxy()
  File "C:\Users\x1090102\PycharmProjects\flask_view\venv\Lib\site-packages\srtranslator\translators\deepl_scrap.py", line 94, in _rotate_proxy
    self.driver = create_driver(proxy)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x1090102\PycharmProjects\flask_view\venv\Lib\site-packages\srtranslator\translators\selenium_utils.py", line 59, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'proxy'

**Comment by h9052300** [comment]
Updated and fixed.
thx.
